## Matrix multiplication column perspective
#### $\mathbf{A}\mathbf{B}= \sum_{k=1}^{n}$ (column k of A)(row k of B)$=\sum_{k=1}^{n}A\begin{bmatrix}:,&k \end{bmatrix}B\begin{bmatrix}k, & : \end{bmatrix}^T$
#### Matrix multiplication column perspective is a weighted linear combination of the columns and the rows
#### The sum of the columns of the first matrix weighted by the elements of the columns of the second matrix
#### in essence you have two vectors, vector one is the first column of the first matrix scaled by the first element of the first column of the second matrix and the second vector is the first column of the first matrix and the second element of the first column of the second matrix

$\begin{Bmatrix}
 1 & 2 \\
 3 & 4 \end{Bmatrix}\times\
 \begin{Bmatrix}
 a & b \\
 c & d \end{Bmatrix} = \begin{Bmatrix}
 a\times\begin{bmatrix}
 1 \\
 3 \end{bmatrix} + c\times\begin{bmatrix}
 2 \\
 4 \end{bmatrix} &
 b\times\begin{bmatrix}
 1 \\
 3 \end{bmatrix} + d\times\begin{bmatrix}
 2 \\
 4 \end{bmatrix}
 \end{Bmatrix}$


$\begin{Bmatrix}
 1 & 2  \\
 3 & 4 \end{Bmatrix} \times
 \begin{Bmatrix}
 5 & 6 \\
 7 & 8 \end{Bmatrix} = 
 \begin{Bmatrix}
 5\begin{bmatrix}1\\3\end{bmatrix} +7\begin{bmatrix}2\\4\end{bmatrix}  &
 6\begin{bmatrix}1\\3\end{bmatrix} + 8\begin{bmatrix}2\\4\end{bmatrix}
 \end{Bmatrix} =
 \begin{Bmatrix}
 \begin{bmatrix}5\\15\end{bmatrix} + \begin{bmatrix}14\\28\end{bmatrix} &
 \begin{bmatrix}6\\18\end{bmatrix} + \begin{bmatrix}16\\32\end{bmatrix} 
 \end{Bmatrix} =
 \begin{Bmatrix}
 19 & 22 \\
 43 & 50 \end{Bmatrix} $
 $\begin{Bmatrix}
 1 & 2 & 3 \\
 4 & 5 & 6 
 \end{Bmatrix}\times
 \begin{Bmatrix}
 4 & 5 \\
 6 & 7 \\
 8 & 9 \end{Bmatrix}=
 \begin{Bmatrix} 
 4\begin{bmatrix}1\\4\end{bmatrix} + 6\begin{bmatrix}2\\5\end{bmatrix} + 8\begin{bmatrix}3\\6\end{bmatrix} &
 5\begin{bmatrix}1\\4\end{bmatrix} + 7\begin{bmatrix}2\\5\end{bmatrix} + 9\begin{bmatrix}3\\6\end{bmatrix}
 \end{Bmatrix} = \begin{Bmatrix}
 \begin{bmatrix}4\\16\end{bmatrix} + \begin{bmatrix}12\\30\end{bmatrix} + \begin{bmatrix}24\\48\end{bmatrix} &
 \begin{bmatrix}5\\20\end{bmatrix} + \begin{bmatrix}14\\35\end{bmatrix} + \begin{bmatrix}27\\54\end{bmatrix} 
 \end{Bmatrix} =
 \begin{Bmatrix}
 40 & 46 \\
 94 & 109
 \end{Bmatrix}$

$\begin{Bmatrix}
 1 & 2 \\
 3 & 4 \\
 5 & 6 
 \end{Bmatrix}\times\begin{Bmatrix}
 4 & 5 & 6 \\
 7 & 8 & 9 
 \end{Bmatrix}=
 \begin{Bmatrix}
 4\begin{bmatrix} 1\\3\\5 \end{bmatrix}+ 7 \begin{bmatrix} 2\\4\\6 \end{bmatrix} & 
 5\begin{bmatrix} 1\\3\\5 \end{bmatrix}+ 8 \begin{bmatrix} 2\\4\\6 \end{bmatrix} &
 6\begin{bmatrix} 1\\3\\5 \end{bmatrix}+ 9 \begin{bmatrix} 2\\4\\6 \end{bmatrix} 
 \end{Bmatrix}= \begin{Bmatrix}
 \begin{bmatrix} 4\\12\\20 \end{bmatrix}+ \begin{bmatrix} 14\\28\\42 \end{bmatrix} &
 \begin{bmatrix} 5\\15\\25 \end{bmatrix}+ \begin{bmatrix} 16\\32\\48 \end{bmatrix} &
 \begin{bmatrix} 6\\18\\30 \end{bmatrix}+ \begin{bmatrix} 18\\36\\54 \end{bmatrix} 
 \end{Bmatrix} = \begin{Bmatrix}
 18 & 21 & 24 \\
 40 & 47 & 54 \\
 62 & 73 & 84
 \end{Bmatrix}$
 #### This interpretation of matrix multiplication is useful in statistics and AI (machine learning): Linear model fitting (Linear least squares modeling https://en.wikipedia.org/wiki/Linear_least_squares) The left matrix will contain the regressors and the right matrix contains the coefficients. The goal of linear model fitting is that the weighted combination of the regressors and coefficients best model the existsting data

## Matrix multiplication column perspective

In [1]:
import numpy as np

# main function
def MM_COL_PERS(M1,M2):
    if matrix_multiplication_defined(M1,M2):
        ACC = np.array([]) # general accumulator, a numpy array allow us to reshape and transpose
        zeros = make_zeros(M1) # zero vector used as a dummy to allow easy vector addition
        return inner_logic(M1,M2,ACC,zeros,0,0)
    else:
        return "matrix multiplication is not defined for these matrices"

# function for the operational logic
def inner_logic(M1,M2,ACC,zeros,row,col):
    if col < M2.shape[1]:
        if row < M1.shape[1]:
        # take the n-th column = n-th row of the M1 transposed
            column = M1.T[row] # the original matrix is transposed so the column becomes the row
        # the n-th element of the m-th column of the the second matrix
            scalar = M2.T[col][row] # the original matrix is transposed so the column becomes the row
            vector = scalar * column
            zeros = zeros + vector # using a dummy variable here prevents calling another function to add the vectors
            return inner_logic(M1,M2,ACC,zeros,row+1,col)
        else:
            ACC = np.append(ACC, zeros)
            zeros = make_zeros(M1) # resetting our dummy variable
            row = 0 # resetting the row variable
            return inner_logic(M1,M2,ACC,zeros,row,col+1)
    else:
        return ACC.reshape(M1.shape[0],M2.shape[1]).T # we need to reshape and transpose the accumulator (Python)

# pure helper functions
def make_zeros(M):
    return np.zeros((1,M.shape[0]))

def matrix_multiplication_defined(M1,M2):
    if M1.shape[1] == M2.shape[0]:
        return True 
    else:
        return False




### Tests 

In [2]:
A = np.arange(1,7).reshape(1,6)
#print(A)
B = np.arange(4,10).reshape(3,2)
#print(B)
AT = np.arange(1,37).reshape(6,6)
print(AT)
BT = np.arange(5,41).reshape(6,6)
print(BT)
AX = np.arange(1,5).reshape(2,2)
#print(AX)
BX = np.arange(5,9).reshape(2,2)
#print(BX)

print("python result")
print(np.matmul(AT,BT))
print("result using our function")
print(MM_COL_PERS(AT,BT))
print("test should be a zero matrix of same size")
print(np.matmul(AT,BT)-MM_COL_PERS(AT,BT))


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[ 5  6  7  8  9 10]
 [11 12 13 14 15 16]
 [17 18 19 20 21 22]
 [23 24 25 26 27 28]
 [29 30 31 32 33 34]
 [35 36 37 38 39 40]]
python result
[[ 525  546  567  588  609  630]
 [1245 1302 1359 1416 1473 1530]
 [1965 2058 2151 2244 2337 2430]
 [2685 2814 2943 3072 3201 3330]
 [3405 3570 3735 3900 4065 4230]
 [4125 4326 4527 4728 4929 5130]]
result using our function
[[ 525.  546.  567.  588.  609.  630.]
 [1245. 1302. 1359. 1416. 1473. 1530.]
 [1965. 2058. 2151. 2244. 2337. 2430.]
 [2685. 2814. 2943. 3072. 3201. 3330.]
 [3405. 3570. 3735. 3900. 4065. 4230.]
 [4125. 4326. 4527. 4728. 4929. 5130.]]
test should be a zero matrix of same size
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
